# Generated by Django 5.0.3 on 2024-05-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='activate'),
        ),
    ]
