# Generated by Django 5.0.3 on 2024-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_activate',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='activated'),
        ),
    ]
